export type ResaleStatus = 'pending' | 'approved' | 'rejected';
export type StatusFilter = 'all' | ResaleStatus;

export interface ResaleTicket {
  id: string;
  eventId: string;
  eventName: string;
  eventDate: string;
  category: string;
  quantity: number;
  seller: { name: string; initials: string; rating: number; transactions: number };
  originalPrice: number;
  resalePrice: number;
  status: ResaleStatus;
  listedDate: string;
  listedAt: string; // ISO date: 'YYYY-MM-DD'
}

export const STATUS_CONFIG: Record<ResaleStatus, { label: string; bg: string; color: string; border: string }> = {
  pending:  { label: 'Pending',  bg: '#fffbeb', color: '#92400e', border: '#fcd34d' },
  approved: { label: 'Approved', bg: '#ecfdf5', color: '#065f46', border: '#6ee7b7' },
  rejected: { label: 'Rejected', bg: '#fef2f2', color: '#991b1b', border: '#fca5a5' },
};

export const STATUS_FILTERS: { value: StatusFilter; label: string }[] = [
  { value: 'all',      label: 'All' },
  { value: 'pending',  label: 'Pending' },
  { value: 'approved', label: 'Approved' },
  { value: 'rejected', label: 'Rejected' },
];

export const MOCK_TICKETS: ResaleTicket[] = [
  // ── evt-001: Coldplay World Tour — Hanoi ─────────────────────────────────
  {
    id: '1',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'GA Zone · Green Tier',
    quantity: 2,
    seller: { name: 'T. Tran', initials: 'TT', rating: 4.9, transactions: 12 },
    originalPrice: 1200000,
    resalePrice: 1320000,
    status: 'pending',
    listedDate: '2 hours ago',
    listedAt: '2026-03-26',
  },
  {
    id: '2',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'VIP Zone · Gold Tier',
    quantity: 1,
    seller: { name: 'L. Mai', initials: 'LM', rating: 5.0, transactions: 3 },
    originalPrice: 2800000,
    resalePrice: 2800000,
    status: 'pending',
    listedDate: '1 day ago',
    listedAt: '2026-03-25',
  },
  {
    id: '3',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'SVIP Zone · Platinum',
    quantity: 1,
    seller: { name: 'H. Nguyen', initials: 'HN', rating: 4.8, transactions: 5 },
    originalPrice: 4500000,
    resalePrice: 4950000,
    status: 'pending',
    listedDate: '3 hours ago',
    listedAt: '2026-03-26',
  },
  {
    id: '4',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'GA Zone · Green Tier',
    quantity: 4,
    seller: { name: 'M. Vo', initials: 'MV', rating: 4.6, transactions: 15 },
    originalPrice: 1200000,
    resalePrice: 1320000,
    status: 'approved',
    listedDate: '2 days ago',
    listedAt: '2026-03-24',
  },
  {
    id: '5',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'VIP Zone · Gold Tier',
    quantity: 2,
    seller: { name: 'B. Dang', initials: 'BD', rating: 4.3, transactions: 7 },
    originalPrice: 2800000,
    resalePrice: 3080000,
    status: 'approved',
    listedDate: '4 days ago',
    listedAt: '2026-03-22',
  },
  {
    id: '6',
    eventId: 'evt-001',
    eventName: 'Coldplay World Tour — Hanoi',
    eventDate: '14/09/2025',
    category: 'GA Zone · Blue Tier',
    quantity: 1,
    seller: { name: 'C. Hoang', initials: 'CH', rating: 3.8, transactions: 2 },
    originalPrice: 900000,
    resalePrice: 1260000,
    status: 'rejected',
    listedDate: '6 days ago',
    listedAt: '2026-03-20',
  },

  // ── evt-002: Imagine Dragons Live ─────────────────────────────────────────
  {
    id: '7',
    eventId: 'evt-002',
    eventName: 'Imagine Dragons Live',
    eventDate: '22/10/2025',
    category: 'VIP Zone',
    quantity: 3,
    seller: { name: 'A. Nguyen', initials: 'AN', rating: 4.8, transactions: 8 },
    originalPrice: 1500000,
    resalePrice: 1650000,
    status: 'approved',
    listedDate: '3 days ago',
    listedAt: '2026-03-23',
  },
  {
    id: '8',
    eventId: 'evt-002',
    eventName: 'Imagine Dragons Live',
    eventDate: '22/10/2025',
    category: 'GA Zone',
    quantity: 2,
    seller: { name: 'P. Le', initials: 'PL', rating: 4.5, transactions: 4 },
    originalPrice: 800000,
    resalePrice: 880000,
    status: 'pending',
    listedDate: '1 day ago',
    listedAt: '2026-03-25',
  },
  {
    id: '9',
    eventId: 'evt-002',
    eventName: 'Imagine Dragons Live',
    eventDate: '22/10/2025',
    category: 'SVIP Zone',
    quantity: 1,
    seller: { name: 'Q. Bui', initials: 'QB', rating: 5.0, transactions: 20 },
    originalPrice: 3200000,
    resalePrice: 3200000,
    status: 'approved',
    listedDate: '5 days ago',
    listedAt: '2026-03-21',
  },
  {
    id: '10',
    eventId: 'evt-002',
    eventName: 'Imagine Dragons Live',
    eventDate: '22/10/2025',
    category: 'GA Zone',
    quantity: 3,
    seller: { name: 'N. Pham', initials: 'NP', rating: 3.9, transactions: 1 },
    originalPrice: 800000,
    resalePrice: 1120000,
    status: 'rejected',
    listedDate: '7 days ago',
    listedAt: '2026-03-19',
  },

  // ── evt-003: Radiohead Asia Tour ──────────────────────────────────────────
  {
    id: '11',
    eventId: 'evt-003',
    eventName: 'Radiohead Asia Tour',
    eventDate: '05/11/2025',
    category: 'SVIP Zone',
    quantity: 1,
    seller: { name: 'K. Pham', initials: 'KP', rating: 4.7, transactions: 6 },
    originalPrice: 3500000,
    resalePrice: 3850000,
    status: 'pending',
    listedDate: '5 hours ago',
    listedAt: '2026-03-26',
  },
  {
    id: '12',
    eventId: 'evt-003',
    eventName: 'Radiohead Asia Tour',
    eventDate: '05/11/2025',
    category: 'VIP Zone',
    quantity: 2,
    seller: { name: 'D. Trinh', initials: 'DT', rating: 4.4, transactions: 9 },
    originalPrice: 2200000,
    resalePrice: 2420000,
    status: 'pending',
    listedDate: '12 hours ago',
    listedAt: '2026-03-26',
  },
  {
    id: '13',
    eventId: 'evt-003',
    eventName: 'Radiohead Asia Tour',
    eventDate: '05/11/2025',
    category: 'GA Zone',
    quantity: 4,
    seller: { name: 'E. Ly', initials: 'EL', rating: 4.1, transactions: 3 },
    originalPrice: 1100000,
    resalePrice: 1210000,
    status: 'approved',
    listedDate: '3 days ago',
    listedAt: '2026-03-23',
  },

  // ── evt-004: Bruno Mars Concert ───────────────────────────────────────────
  {
    id: '14',
    eventId: 'evt-004',
    eventName: 'Bruno Mars Concert',
    eventDate: '18/12/2025',
    category: 'GA Zone',
    quantity: 2,
    seller: { name: 'T. Le', initials: 'TL', rating: 3.5, transactions: 2 },
    originalPrice: 1000000,
    resalePrice: 1400000,
    status: 'rejected',
    listedDate: '5 days ago',
    listedAt: '2026-03-21',
  },
  {
    id: '15',
    eventId: 'evt-004',
    eventName: 'Bruno Mars Concert',
    eventDate: '18/12/2025',
    category: 'VIP Zone',
    quantity: 1,
    seller: { name: 'F. Ngo', initials: 'FN', rating: 4.9, transactions: 11 },
    originalPrice: 2500000,
    resalePrice: 2750000,
    status: 'pending',
    listedDate: '2 days ago',
    listedAt: '2026-03-24',
  },
  {
    id: '16',
    eventId: 'evt-004',
    eventName: 'Bruno Mars Concert',
    eventDate: '18/12/2025',
    category: 'SVIP Zone',
    quantity: 1,
    seller: { name: 'G. Dinh', initials: 'GD', rating: 4.6, transactions: 8 },
    originalPrice: 4000000,
    resalePrice: 4400000,
    status: 'approved',
    listedDate: '6 days ago',
    listedAt: '2026-03-20',
  },

  // ── evt-005: Ed Sheeran Mathematics Tour ──────────────────────────────────
  {
    id: '17',
    eventId: 'evt-005',
    eventName: 'Ed Sheeran Mathematics Tour',
    eventDate: '03/01/2026',
    category: 'GA Zone · Orange Tier',
    quantity: 2,
    seller: { name: 'H. Truong', initials: 'HT', rating: 4.7, transactions: 6 },
    originalPrice: 1300000,
    resalePrice: 1430000,
    status: 'pending',
    listedDate: '4 hours ago',
    listedAt: '2026-03-26',
  },
  {
    id: '18',
    eventId: 'evt-005',
    eventName: 'Ed Sheeran Mathematics Tour',
    eventDate: '03/01/2026',
    category: 'VIP Zone · Red Tier',
    quantity: 1,
    seller: { name: 'I. Cao', initials: 'IC', rating: 4.2, transactions: 4 },
    originalPrice: 2600000,
    resalePrice: 2860000,
    status: 'pending',
    listedDate: '1 day ago',
    listedAt: '2026-03-25',
  },
  {
    id: '19',
    eventId: 'evt-005',
    eventName: 'Ed Sheeran Mathematics Tour',
    eventDate: '03/01/2026',
    category: 'GA Zone · Orange Tier',
    quantity: 3,
    seller: { name: 'J. Luu', initials: 'JL', rating: 5.0, transactions: 18 },
    originalPrice: 1300000,
    resalePrice: 1300000,
    status: 'approved',
    listedDate: '4 days ago',
    listedAt: '2026-03-22',
  },
  {
    id: '20',
    eventId: 'evt-005',
    eventName: 'Ed Sheeran Mathematics Tour',
    eventDate: '03/01/2026',
    category: 'SVIP Zone',
    quantity: 1,
    seller: { name: 'K. Ha', initials: 'KH', rating: 3.2, transactions: 1 },
    originalPrice: 5000000,
    resalePrice: 6500000,
    status: 'rejected',
    listedDate: '8 days ago',
    listedAt: '2026-03-18',
  },
];

export function formatCurrency(amount: number) {
  return amount.toLocaleString('vi-VN') + ' ₫';
}
