// types/enums.ts
export enum OrganizationRole {
  OWNER = 'OWNER',
  MANAGER = 'MANAGER',
  COORDINATOR = 'COORDINATOR',
  SCANNER = 'SCANNER',
  VIEWER = 'VIEWER',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TicketTypeStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  SOLD_OUT = 'SOLD_OUT',
  DEACTIVATED = 'DEACTIVATED',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}
